services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-bot
    volumes:
      - ./data:/app/data      # Persist database
    env_file:
      - .env                  # Load environment variables
    restart: unless-stopped
